---
- name: Teardown Jenkins and Clean Up Environment
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Delete Jenkins Service
      kubernetes.core.k8s:
        state: absent
        namespace: jenkins
        kind: Service
        name: jenkins-service

    - name: Delete Jenkins Deployment
      kubernetes.core.k8s:
        state: absent
        namespace: jenkins
        kind: Deployment
        name: jenkins

    - name: Delete Jenkins PVC
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: jenkins-pvc
            namespace: jenkins

    - name: Delete Jenkins PV
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: jenkins-pv

    - name: Delete Jenkins Namespace
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: jenkins
