ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/backend-protocol: "http"
  hosts:
    - host: gitea.ojaydiddy.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - gitea.ojaydiddy.site
