entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
