---
- name: Deploy Jenkins to Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Create Jenkins namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: jenkins
        state: present

    - name: Create PersistentVolume for Jenkins
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: jenkins-pv
          spec:
            storageClassName: manual
            capacity:
              storage: 5Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: /mnt/data/jenkins

    - name: Create PersistentVolumeClaim for Jenkins
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: jenkins-pvc
            namespace: jenkins
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: manual

    - name: Deploy Jenkins Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: jenkins
            namespace: jenkins
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: jenkins
            template:
              metadata:
                labels:
                  app: jenkins
              spec:
                containers:
                  - name: jenkins
                    image: jenkins/jenkins:lts
                    ports:
                      - containerPort: 8080
                    volumeMounts:
                      - name: jenkins-data
                        mountPath: /var/jenkins_home
                volumes:
                  - name: jenkins-data
                    emptyDir: {}
                    
    - name: Create Jenkins Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: jenkins-service
            namespace: jenkins
          spec:
            selector:
              app: jenkins
            ports:
              - port: 8080
                targetPort: 8080
            type: ClusterIP
